# Site
repository: dtrochow/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dominik Trochowski
title: Embedded Software Engineer
email: dominik.trochowski@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: dtrochow
github_username:  dtrochow
linkedin_username: dominik-trochowski-05002a227
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dominik and I'm a passionate Software Engineer specializing in embedded systems projects. I like taking on new challenges from inception to design and implementation,
  which allows me to have a tangible impact on the final product. In addition to this, I excel in leading teams towards task completion. Beyond that, I also thrive on taking on new projects from scratch,
  starting with an idea, crafting the design, and seeing it through to implementation. This approach gives me a real influence on the final product.
  In my free time, I love working on personal electronics projects, refining my skills, and exploring creative solutions.


  Skills: <mark>C/C++</mark> <mark>Debugging</mark> <mark>Docker</mark> <mark>CMake</mark> <mark>Unit Tests</mark> <mark>Python</mark> <mark>RTOS</mark> <mark>Linux</mark> <mark>Assembler (basics)</mark> <mark>design patterns</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Solidigm
        link: https://www.solidigm.com/
        link_text: solidigm.com
        sub_title: Software Development Engineer
        caption: January 2022 - Present
        quote: >
          NAND Product Solutions Group
        description: | # this will include new lines to allow paragraphs
          I am currently involved in the security features development and enablement (design, implementation and unit/manual testing).
          In my team I am taking a part in design of final solutions and then implementation in the SSD firmware.
      - layout: left
        title: Intel
        link: https://www.intel.com/
        link_text: intel.com
        sub_title: Software Development Engineer
        caption: June 2021 - December 2021
        quote: >
          NAND Product Solutions Group
        description: | # this will include new lines to allow paragraphs
          I continued my work as a Security Team member. I started working on the security features, fixing bugs, extending
          the simulator capabilities and setting up the new python CI testing framework from scratch.
      - layout: left
        title: Intel
        link: https://www.intel.com/
        link_text: intel.com
        sub_title: Software Development Engineer Intern
        caption: February 2021 - June 2021
        quote: >
          NAND Product Solutions Group
        description: | # this will include new lines to allow paragraphs
          I started my internship in Security Team, which was developing the security features in SSD drives (TCG).
          I was involved in setting up a new repository with CI using Quick Build tool and also working on a simulation tasks.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: WSB Merito University Gdańsk
        caption: March 2021 - October 2022
        sub_title: IT Project Management
        quote: >
          Master's degree
        description: | # this will include new lines to allow paragraphs
          My second degree in IT Project Management provided me with expertise in resolving issues within IT projects and implementing Agile methodologies.
          This education significantly strengthened my leadership abilities, enabling me to guide teams towards successful project outcomes.
      - layout: left
        title: Gdańsk University of Technology
        caption: October 2018 - February 2021
        sub_title: Automation and Robotics
        quote: >
          Engineer's degree - Specialization in Robotics and Mechatronics Systems
        description: | # this will include new lines to allow paragraphs
          During my studies in Automation and Robotics, I gained comprehensive knowledge in control systems, electronics, programming, and solving complex problems.
          I was an active member of the Scientific Club of Automation Students *(NKSA - Naukowe Koło Studentów Automatyki)* during my studies also.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering and electronics some of my other interests and hobbies are:
      - **Designing 3D** parts and **3D printing**
      - Cycling, gym, rollerblading
      - Extending automation in my home (*Home Assistant*)
      - Board games
      - Learning **Rust** programming language
      - Electronics projects and
        here is an example of one of my projects, which is *RGB Led Cube 4x4x4* (source code on my Github account). I designed and made it from the scratch.

        [Led Cube RGB 4x4x4](https://github.com/dtrochow/LED_Cube_RGB)

        ![led_cube](images/led_cube.jpg "Led Cube"){:style="width: 60vw;"}

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: dtrochow/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
